// GENERATED BY SEJ RUNTIME RESOLVER. DO NOT EDIT.
// sourceSEJ: contracts/sej/materialize-ascii-render-kernel-node.sej.v1.json
// contractKey: defracto.sej.materialize-ascii-render-kernel-node.v1
// Generated conformance test for defracto.kernels.ascii_render_kernel.
// This file is resolver-materialized and owns no visual truth.

'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const { renderAsciiProjection } = require('../../kernels/ascii-render-kernel/ascii-render-kernel.js');

const fixturePath = path.resolve(__dirname, '../../examples/kernels/ascii-render-kernel/founding-conveyor.visual-projection-model.v1.json');
const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));
const options = {
  visualProjectionModelPath: 'examples/kernels/ascii-render-kernel/founding-conveyor.visual-projection-model.v1.json',
  targetArtifactPath: 'reports/sketches/slice-007h-sej-projected-ascii-render-kernel-conveyor.ascii'
};

const expectedText = [
  '+----------------------+',
  '|     story intent     |',
  '+----------------------+',
  '            v',
  '+----------------------+',
  '|    canonical spec    |',
  '+----------------------+',
  '            v',
  '+----------------------+',
  '| semantic kernel SEJ  |',
  '+----------------------+',
  '            v',
  '+----------------------+',
  '| projection manifest  |',
  '+----------------------+',
  '            v',
  '+----------------------+',
  '| generated kernel js  |',
  '+----------------------+',
  '            v',
  '+----------------------+',
  '|     visual proof     |',
  '+----------------------+'
].join('\n');

test('renders the kernel conveyor deterministically', () => {
  const first = renderAsciiProjection(fixture, options);
  const second = renderAsciiProjection(fixture, options);

  assert.equal(first.renderedText, expectedText);
  assert.equal(second.renderedText, expectedText);
  assert.equal(first.contentHash, second.contentHash);
  assert.equal(first.lineCount, expectedText.split('\n').length);
  assert.equal(first.visualProjectionModelPath, options.visualProjectionModelPath);
  assert.equal(first.targetArtifactPath, options.targetArtifactPath);
});

test('fails closed on unsupported connectors', () => {
  const invalid = JSON.parse(JSON.stringify(fixture));
  invalid.edges[0].connector = 'diagonal';
  assert.throws(() => renderAsciiProjection(invalid, options), /unsupported connector/i);
});