// GENERATED BY DEFRACTO SEJ MATERIALIZATION. DO NOT EDIT.
// sourceSEJ: contracts/sej/materialize-ascii-render-kernel-node.sej.v1.json
// contractKey: defracto.sej.materialize-ascii-render-kernel-node.v1

'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const { spawnSync } = require('node:child_process');

const targetPath = path.resolve(__dirname, "../../generated/kernels/ascii-render-kernel.cjs");
const fixturePath = path.resolve(__dirname, "../../source/visual-intent/founding-conveyor.visual-projection-model.v1.json");
const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));
const options = {
  visualProjectionModelPath: "source/visual-intent/founding-conveyor.visual-projection-model.v1.json",
  targetArtifactPath: "conveyor/runs/2026/06/21/sketches/slice-007h-sej-projected-ascii-render-kernel-conveyor.ascii"
};

function runKernel(input) {
  const run = spawnSync(process.execPath, [targetPath], { encoding: "utf8", input: JSON.stringify(input) });
  assert.equal(run.status, 0, run.stderr);
  return JSON.parse(run.stdout || "{}");
}

test('runs the generated kernel wrapper through the resolver doorway', () => {
  const first = runKernel({ visualProjectionModel: fixture, ...options });
  const second = runKernel({ visualProjectionModel: fixture, ...options });

  assert.equal(first.status, "passed");
  assert.equal(second.status, "passed");
  assert.equal(first.evidence.contractKey, "defracto.sej.ascii-render-kernel.semantic-kernel.v1");
  assert.equal(second.evidence.contractKey, "defracto.sej.ascii-render-kernel.semantic-kernel.v1");
});